name: 🎯 NSITE Project Milestone
description: Track NSITE decision gates and project milestones (ATP DG, F2I DG, ORR, PPR, CA, etc.)
title: "🎯 MILESTONE: [Milestone Type] - [Project Name]"
labels: ["nsite-milestone", "decision-gate", "project-milestone"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## NSITE Project Milestone Tracking
        Track NSITE decision gates, reviews, and project milestones throughout the solution project lifecycle in the same style as touchpoints.

  - type: input
    id: solution_project_name
    attributes:
      label: Solution Project Name
      description: Name of the NSITE solution project
      placeholder: "Earth Science Data Portal Enhancement"
    validations:
      required: true

  - type: dropdown
    id: nsite_milestone_type
    attributes:
      label: NSITE Milestone Type
      description: Type of NSITE milestone or decision gate
      options:
        - Authority to Proceed Decision Gate (ATP DG)
        - Formulation to Implementation Decision Gate (F2I DG)
        - Operational Readiness Review (ORR)
        - Project Closeout Decision Gate
        - Periodic Project Review (PPR)
        - Continuation Assessment (CA)
        - Project Formal Milestone Review
        - Contract/Agreement Decision Point
        - DAAC Selection Milestone
        - Other NSITE Milestone (specify in description)
    validations:
      required: true

  - type: input
    id: target_date
    attributes:
      label: Target Milestone Date
      description: Planned date for milestone completion
      placeholder: "YYYY-MM-DD"
    validations:
      required: true

  - type: dropdown
    id: current_status
    attributes:
      label: Current Milestone Status
      description: Current status of this NSITE milestone
      options:
        - Planned - Milestone scheduled, preparation not started
        - In Preparation - Actively preparing materials and coordination
        - Under Review - Review in progress by NSITE MO/decision authorities
        - Completed - GO Decision - Milestone successfully completed
        - Completed - Conditional GO - Milestone completed with conditions/actions
        - Deferred - Milestone postponed to later date
        - NO-GO Decision - Milestone failed, requires remediation
    validations:
      required: true

  - type: textarea
    id: milestone_objectives
    attributes:
      label: Milestone Objectives & Success Criteria
      description: What are the key objectives and success criteria for this NSITE milestone?
      placeholder: "Key decisions to be made, objectives to achieve, entrance/success criteria per NSITE requirements..."
    validations:
      required: true

  - type: textarea
    id: required_deliverables
    attributes:
      label: Required Deliverables
      description: What deliverables are required for this NSITE milestone?
      placeholder: "Presentations, documentation, project plans, agreements, decision memoranda..."
    validations:
      required: true

  - type: checkboxes
    id: nsite_voting_participants
    attributes:
      label: NSITE Decision Gate Voting Participants
      description: Who participates in voting for this milestone? (All must vote GO)
      options:
        - label: NSITE MO Project Manager (PM)
        - label: NSITE MO Project Scientist (PS)
        - label: NASA HQ Program Scientist (PgS) - Optional
        - label: NASA HQ Program Manager (PgM) - Optional
        - label: Earth Action Advocate - Optional
        - label: ESDIS Representative (for data solutions)
        - label: DAAC Representative (for data solutions)

  - type: checkboxes
    id: preparation_activities
    attributes:
      label: Milestone Preparation Activities
      description: Select preparation activities needed for this NSITE milestone
      options:
        - label: Presentation Materials Development
        - label: Project Plan/Documentation Updates
        - label: Stakeholder Coordination and Alignment
        - label: Technical Documentation Review
        - label: Budget/Cost Analysis Validation
        - label: Risk Assessment Updates
        - label: Contract/Agreement Coordination
        - label: DAAC/ESDIS Coordination (if applicable)

  - type: dropdown
    id: project_phase
    attributes:
      label: NSITE Project Phase
      description: Which NSITE project phase is this milestone associated with?
      options:
        - Pre-Formulation Phase
        - Formulation Phase
        - Implementation Phase
        - Operations Phase
        - Closeout Phase
    validations:
      required: true

  - type: textarea
    id: entrance_criteria
    attributes:
      label: Entrance Criteria
      description: What must be completed before this milestone can occur?
      placeholder: "Required documentation, prior milestones, stakeholder approvals, contract establishment..."
    validations:
      required: false

  - type: textarea
    id: decision_memorandum_requirements
    attributes:
      label: Decision Memorandum Requirements
      description: What will be documented in the Decision Memorandum for this milestone?
      placeholder: "Decision rationale, conditions, action items, signatures required..."
    validations:
      required: false

  - type: dropdown
    id: milestone_criticality
    attributes:
      label: Milestone Criticality to Project
      description: How critical is this milestone to solution project success?
      options:
        - Critical - Project cannot continue without successful completion
        - High - Significant impact on project success and timeline
        - Moderate - Important for project optimization and compliance
        - Administrative - Required but minimal impact on technical success
    validations:
      required: true

  - type: textarea
    id: risks_and_mitigation
    attributes:
      label: Risks and Mitigation Strategies
      description: What risks could affect milestone success and how will they be mitigated?
      placeholder: "Technical risks, schedule concerns, stakeholder availability, documentation quality..."
    validations:
      required: false

  - type: textarea
    id: coordination_requirements
    attributes:
      label: Coordination Requirements
      description: What coordination is needed with NSITE MO and other stakeholders?
      placeholder: "NSITE MO review meetings, stakeholder briefings, external approvals, contract coordination..."
    validations:
      required: false

  - type: checkboxes
    id: follow_up_actions
    attributes:
      label: Potential Follow-up Actions
      description: What actions may be required after milestone completion?
      options:
        - label: Update Project Plan based on decisions
        - label: Establish/modify contracts or agreements
        - label: Schedule follow-up reviews or assessments
        - label: Communicate decisions to stakeholders
        - label: Archive Decision Memorandum per IM Plan
        - label: Update risk register and mitigation plans
        - label: Coordinate with DAAC/ESDIS (if applicable)

  - type: input
    id: next_milestone
    attributes:
      label: Next Planned Milestone
      description: What is the next major milestone after this one?
      placeholder: "Next NSITE decision gate or major project milestone..."
    validations:
      required: false
