name: 📈 Program Performance Management
description: Track strategic program metrics, outcomes, and executive-level performance management
title: "📈 PERFORMANCE: [Strategic Performance Focus]"
labels: ["program-performance", "executive-dashboard", "strategic-metrics"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Strategic Program Performance Management
        Monitor program-wide performance metrics, track strategic outcomes, and manage executive-level performance initiatives across all solution projects.

  - type: input
    id: performance_focus_title
    attributes:
      label: Strategic Performance Focus Title
      description: Brief title describing the strategic performance area
      placeholder: "FY25 Program Portfolio Strategic Performance Assessment"
    validations:
      required: true

  - type: dropdown
    id: strategic_performance_category
    attributes:
      label: Strategic Performance Category
      description: Type of strategic performance measurement
      options:
        - Overall Program Strategic Effectiveness
        - Cross-Project Portfolio Performance
        - Strategic Stakeholder Impact/Satisfaction
        - Program Timeline/Milestone Performance
        - Strategic Resource Efficiency/ROI
        - Cross-Agency Partnership Effectiveness
        - Technology Integration Success
        - Strategic Innovation/Transformation Metrics
    validations:
      required: true

  - type: dropdown
    id: performance_timeframe
    attributes:
      label: Strategic Performance Timeframe
      description: Period covered by this strategic performance assessment
      options:
        - Current Fiscal Year
        - Current Program Cycle
        - Cross-Cycle Strategic Comparison
        - Real-time Strategic Monitoring
        - Long-term Strategic Trend Analysis
        - Executive Quarterly Review
    validations:
      required: true

  - type: textarea
    id: strategic_performance_metrics
    attributes:
      label: Strategic Performance Metrics
      description: Key strategic metrics being tracked at program level
      placeholder: "Program goal achievement rates, stakeholder impact metrics, strategic milestone completion, ROI measures..."
    validations:
      required: true

  - type: textarea
    id: current_strategic_performance
    attributes:
      label: Current Strategic Performance Status
      description: Latest strategic performance results and executive-level analysis
      placeholder: "Strategic metric values, trend analysis, comparison to program goals, executive implications..."
    validations:
      required: true

  - type: dropdown
    id: strategic_performance_assessment
    attributes:
      label: Strategic Performance Assessment
      description: Executive-level assessment of performance against strategic goals
      options:
        - Exceeding Strategic Expectations - Performance above strategic targets
        - Meeting Strategic Goals - Performance at strategic target levels
        - Below Strategic Expectations - Performance below targets but manageable
        - Strategic Concern - Performance requiring executive attention
        - Strategic Crisis - Performance requiring immediate executive intervention
    validations:
      required: true

  - type: textarea
    id: strategic_performance_drivers
    attributes:
      label: Strategic Performance Drivers
      description: What strategic factors are driving current performance results?
      placeholder: "Program strategy effectiveness, resource allocation, partnership performance, external factors..."
    validations:
      required: true

  - type: textarea
    id: strategic_improvement_opportunities
    attributes:
      label: Strategic Improvement Opportunities
      description: Executive-level opportunities to enhance program performance
      placeholder: "Strategic process optimization, resource reallocation, partnership enhancement, technology advancement..."
    validations:
      required: false

  - type: textarea
    id: executive_strategic_actions
    attributes:
      label: Recommended Executive Strategic Actions
      description: Strategic actions recommended for executive consideration
      placeholder: "Strategic policy changes, resource allocation decisions, partnership initiatives, organizational changes..."
    validations:
      required: true

  - type: dropdown
    id: strategic_action_priority
    attributes:
      label: Strategic Action Priority Level
      description: Urgency of strategic performance actions for executives
      options:
        - Critical Strategic Action Required - Immediate executive intervention
        - High Priority - Executive action needed this quarter
        - Medium Priority - Strategic planning for next cycle
        - Low Priority - Long-term strategic consideration
        - Monitoring - Continue strategic tracking without immediate action
    validations:
      required: true

  - type: checkboxes
    id: executive_reporting_requirements
    attributes:
      label: Executive Reporting Requirements
      description: Where should strategic performance results be communicated?
      options:
        - label: NASA HQ Executive Leadership Briefings
        - label: Program Strategic Review Meetings
        - label: Cross-Agency Executive Coordination
        - label: Congressional/OMB Strategic Reporting
        - label: Strategic Stakeholder Community Updates
        - label: Program Strategic Planning Sessions
