name: 🔗 Cross-Project Strategic Insight
description: Document patterns, trends, and strategic insights spanning multiple solution projects
title: "🔗 STRATEGIC INSIGHT: [Brief Description]"
labels: ["strategic-insight", "executive-dashboard", "cross-project"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Cross-Project Strategic Insights
        Use this template to capture strategic patterns, trends, and insights that span multiple solution projects and inform program-level decision making.

  - type: input
    id: insight_title
    attributes:
      label: Strategic Insight Title
      description: Brief, descriptive title for the cross-project insight
      placeholder: "Stakeholder Engagement Success Patterns Across Solutions"
    validations:
      required: true

  - type: dropdown
    id: insight_category
    attributes:
      label: Insight Category
      description: Type of strategic insight being documented
      options:
        - Cross-Project Best Practice
        - Risk Pattern Recognition  
        - Resource Optimization Opportunity
        - Stakeholder Engagement Trend
        - Process Improvement Insight
        - Success Factor Analysis
        - Partnership Development Pattern
        - Technology Integration Learning
    validations:
      required: true

  - type: textarea
    id: insight_description
    attributes:
      label: Strategic Insight Description
      description: Comprehensive description of the pattern, trend, or strategic learning
      placeholder: "What was observed across projects, why it's strategically significant, and implications for program success..."
    validations:
      required: true

  - type: textarea
    id: supporting_evidence
    attributes:
      label: Supporting Evidence
      description: Specific examples, data, or observations that support this insight
      placeholder: "Project examples, metrics, stakeholder feedback, timeline analysis, cost data..."
    validations:
      required: true

  - type: dropdown
    id: strategic_impact
    attributes:
      label: Strategic Impact Level
      description: How significantly does this insight affect overall program strategy?
      options:
        - Transformational - Requires major program strategy adjustment
        - High - Important for program optimization and resource allocation
        - Medium - Useful for operational improvements across projects
        - Low - Informational for future planning cycles
    validations:
      required: true

  - type: checkboxes
    id: affected_project_types
    attributes:
      label: Affected Solution Project Types
      description: Which types of solution projects does this insight apply to?
      options:
        - label: All Current Solution Projects
        - label: Earth Science Data Solutions
        - label: Climate/Weather Solutions
        - label: Disaster Response Solutions
        - label: Research & Analysis Solutions
        - label: Cross-Agency Partnership Solutions
        - label: Technology Innovation Projects

  - type: textarea
    id: strategic_recommendations
    attributes:
      label: Strategic Recommendations
      description: What program-level actions should be taken based on this insight?
      placeholder: "Policy changes, resource adjustments, process improvements, training initiatives..."
    validations:
      required: true

  - type: textarea
    id: implementation_considerations
    attributes:
      label: Implementation Considerations
      description: What factors should be considered when implementing these recommendations?
      placeholder: "Resource requirements, timeline implications, stakeholder impacts, risk factors..."
    validations:
      required: false

  - type: checkboxes
    id: communication_needs
    attributes:
      label: Strategic Communication Requirements
      description: How should this insight be communicated across the program?
      options:
        - label: NASA HQ Executive Briefing
        - label: All Solution Project Teams
        - label: SNWG Principal Review
        - label: Cross-Agency Stakeholder Notification
        - label: Best Practices Documentation Update
        - label: Training Material Integration
