name: 🤝 Touchpoint Planning
description: Plan and execute stakeholder touchpoints in the co-design process
title: '[TOUCHPOINT] [Project Name] - [Touchpoint Name]'
labels: ['touchpoint', 'stakeholder-engagement', 'planning']
assignees:
  - co-design-lead
body:
  - type: markdown
    attributes:
      value: |
        ## 🤝 Touchpoint Planning Template
        
        Use this template to plan and track stakeholder touchpoints in your co-design process.
        
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: Name of the solution project
      placeholder: e.g., HLS-LL Data Access Portal
    validations:
      required: true
      
  - type: dropdown
    id: touchpoint_type
    attributes:
      label: Touchpoint Type
      description: Select the type of touchpoint being planned
      options:
        - Solution Validation
        - Agency Feedback Survey
        - Solution Intro to Stakeholders
        - Outreach & Screening
        - Requirements Verification
        - Interactive Co-Design
        - Solution Launch/Training
        - Transition/Closeout
    validations:
      required: true
      
  - type: dropdown
    id: phase
    attributes:
      label: Project Phase
      description: Current phase of the solution project
      options:
        - Assessment
        - Pre-Formulation
        - Formulation
        - Implementation
        - Operations
    validations:
      required: true
      
  - type: input
    id: timeline
    attributes:
      label: Target Timeline
      description: Target date or date range for this touchpoint
      placeholder: e.g., March 15, 2025 or March 10-17, 2025
    validations:
      required: true
      
  - type: textarea
    id: stakeholders
    attributes:
      label: Primary Agencies & Stakeholders
      description: List the agencies and key contacts involved
      placeholder: |
        - USDA Forest Service - Jane Smith, GIS Analyst, jane.smith@usda.gov
        - EPA Region 4 - John Doe, Environmental Scientist, john.doe@epa.gov
      render: markdown
    validations:
      required: true
      
  - type: checkboxes
    id: stakeholder_roles
    attributes:
      label: Stakeholder Roles Represented
      description: Check all stakeholder role types that will participate
      options:
        - label: Agency Rep/Lead (Management level)
        - label: IT/Data Support Person
        - label: Operational End User/Decision Maker
        - label: Technical Champion
        - label: External Partner/Contractor
        
  - type: input
    id: expected_participation
    attributes:
      label: Expected Participation
      description: Number of stakeholders expected to participate
      placeholder: e.g., 8-12 stakeholders
    validations:
      required: true
      
  - type: textarea
    id: objectives
    attributes:
      label: Primary Objectives
      description: List the specific objectives for this touchpoint
      placeholder: |
        - Validate current solution approach with agency workflows
        - Collect feedback on user interface
