name: Project Board Automation

on:
  issues:
    types: [opened, labeled, unlabeled, closed, reopened]

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move touchpoint issues
        if: contains(github.event.issue.labels.*.name, 'touchpoint')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: Active Stakeholder Engagement
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move working sessions
        if: contains(github.event.issue.labels.*.name, 'working-session')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: Active Stakeholder Engagement
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move agency-ready issues  
        if: contains(github.event.issue.labels.*.name, '🟢 agency-ready')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: Stakeholder Review
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move decision-needed issues
        if: contains(github.event.issue.labels.*.name, '🟠 decision-needed')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: Stakeholder Review
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move development issues
        if: contains(github.event.issue.labels.*.name, '🟡 in-development')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: In Development
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move solution development issues
        if: contains(github.event.issue.labels.*.name, 'solution-development')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: In Development
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move blocked issues back to Planning
        if: contains(github.event.issue.labels.*.name, '🔴 blocked-external')
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: Planning & Preparation
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move closed issues
        if: github.event.action == 'closed'
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "[TEMPLATE] CoDesign Pipeline"
          column: Complete
          repo-token: ${{ secrets.GITHUB_TOKEN }}
